### ISSUE TITLE
Link doesn't open anything?

### ISSUE THREAD

**Issue by AvLover22** [bjedev/MembeanX#9]
The link to MemebanX just redirects back to the repo??? 
This used to work for me... Pls help

**Comment by AvLover22** [comment]
Did you get sued by membean and take the link down or something?

**Comment by bjedev** [comment]
No. Build it yourself

**Comment by AvLover22** [comment]
I wasn't trying to be mean or anything? Just asking. Im serious because thought maybe Membean made you take it down. Sorry if I offended you just was asking what happened because it used to work. :(

**Comment by AvLover22** [comment]
Ok.... so it still works, I just have to host it myself? Thanks!

**Comment by AvLover22** [comment]
Hey, I created a new link. Thank you! If you don't wanna run it but want others to be able to use it, you can use the link I made and update the readme.md to use this (if you want I don't expect you to, u made it obv): https://membean-x.vercel.app
Thank you, and I hope you have a good rest of your october!

**Comment by AvLover22** [comment]
Thanks
